#!/usr/bin/env python3
# Copyright (C) 2026 Alex Stoyanov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

from __future__ import annotations

CANCELLED = "CANCELLED"
NOT_FOUND = "NOT_FOUND"
PERMISSION_DENIED = "PERMISSION_DENIED"
INVALID_INPUT = "INVALID_INPUT"
RUNTIME_ERROR = "RUNTIME_ERROR"
IO_ERROR = "IO_ERROR"

INPUT_REQUIRED = "INPUT_REQUIRED"
OUTPUT_REQUIRED = "OUTPUT_REQUIRED"
CONFIG_INPUT_REQUIRED = "CONFIG_INPUT_REQUIRED"
CONFIG_JSON_INVALID = "CONFIG_JSON_INVALID"
CONFIG_UNKNOWN_FIELD = "CONFIG_UNKNOWN_FIELD"
CONFIG_INVALID_VALUE = "CONFIG_INVALID_VALUE"
CONFIG_CONFLICT = "CONFIG_CONFLICT"
SHARD_DIR_NOT_FOUND = "SHARD_DIR_NOT_FOUND"
SHARD_DIR_INVALID = "SHARD_DIR_INVALID"
SHARD_DIR_EMPTY = "SHARD_DIR_EMPTY"
SIGNING_KEY_SHARD_DIR_NOT_FOUND = "SIGNING_KEY_SHARD_DIR_NOT_FOUND"
SIGNING_KEY_SHARD_DIR_INVALID = "SIGNING_KEY_SHARD_DIR_INVALID"
SIGNING_KEY_SHARD_DIR_EMPTY = "SIGNING_KEY_SHARD_DIR_EMPTY"

WARNING = "WARNING"
AUTH_PAYLOAD_MISSING = "AUTH_PAYLOAD_MISSING"
AUTH_PAYLOAD_INVALID = "AUTH_PAYLOAD_INVALID"
AUTH_DOC_HASH_MISMATCH = "AUTH_DOC_HASH_MISMATCH"
AUTH_SIGNATURE_INVALID = "AUTH_SIGNATURE_INVALID"
AUTH_FALLBACK_INVALID = "AUTH_FALLBACK_INVALID"
FALLBACK_SECTION_INVALID = "FALLBACK_SECTION_INVALID"
RECOVERY_SHARD_PAYLOADS_IGNORED = "RECOVERY_SHARD_PAYLOADS_IGNORED"
BACKUP_SIGNING_KEY_SHARDING_DISABLED = "BACKUP_SIGNING_KEY_SHARDING_DISABLED"
BACKUP_QR_CHUNK_SIZE_REDUCED = "BACKUP_QR_CHUNK_SIZE_REDUCED"

STABLE_COMMAND_ERROR_CODES = (
    INPUT_REQUIRED,
    OUTPUT_REQUIRED,
    CONFIG_INPUT_REQUIRED,
    CONFIG_JSON_INVALID,
    CONFIG_UNKNOWN_FIELD,
    CONFIG_INVALID_VALUE,
    CONFIG_CONFLICT,
    SHARD_DIR_NOT_FOUND,
    SHARD_DIR_INVALID,
    SHARD_DIR_EMPTY,
    SIGNING_KEY_SHARD_DIR_NOT_FOUND,
    SIGNING_KEY_SHARD_DIR_INVALID,
    SIGNING_KEY_SHARD_DIR_EMPTY,
)

STABLE_GENERIC_ERROR_CODES = (
    CANCELLED,
    NOT_FOUND,
    PERMISSION_DENIED,
    INVALID_INPUT,
    RUNTIME_ERROR,
    IO_ERROR,
)

STABLE_WARNING_CODES = (
    AUTH_PAYLOAD_MISSING,
    AUTH_PAYLOAD_INVALID,
    AUTH_DOC_HASH_MISMATCH,
    AUTH_SIGNATURE_INVALID,
    AUTH_FALLBACK_INVALID,
    FALLBACK_SECTION_INVALID,
    RECOVERY_SHARD_PAYLOADS_IGNORED,
    BACKUP_SIGNING_KEY_SHARDING_DISABLED,
    BACKUP_QR_CHUNK_SIZE_REDUCED,
)

STABLE_BLOCKING_ISSUE_CODES = (
    AUTH_PAYLOAD_MISSING,
    "AUTH_PAYLOAD_MULTIPLE",
    "AUTH_PAYLOAD_DOC_ID_MISMATCH",
    "AUTH_PAYLOAD_FRAME_INVALID",
    AUTH_PAYLOAD_INVALID,
    AUTH_DOC_HASH_MISMATCH,
    AUTH_SIGNATURE_INVALID,
    "PASSPHRASE_SHARDS_UNDER_QUORUM",
    "PASSPHRASE_SHARDS_INVALID",
    "PASSPHRASE_INVALID",
    "PASSPHRASE_REQUIRED",
    "AUTH_REQUIRED",
    "UNLOCK_FAILED",
    "SIGNING_KEY_SHARDS_REQUIRED",
    "SIGNING_KEY_SHARDS_UNDER_QUORUM",
    "SIGNING_KEY_SHARDS_INVALID",
    "PASSPHRASE_REPLACEMENT_NOT_READY",
    "SIGNING_KEY_REPLACEMENT_NOT_READY",
)

__all__ = [
    "AUTH_DOC_HASH_MISMATCH",
    "AUTH_FALLBACK_INVALID",
    "AUTH_PAYLOAD_INVALID",
    "AUTH_PAYLOAD_MISSING",
    "AUTH_SIGNATURE_INVALID",
    "BACKUP_QR_CHUNK_SIZE_REDUCED",
    "BACKUP_SIGNING_KEY_SHARDING_DISABLED",
    "CANCELLED",
    "CONFIG_CONFLICT",
    "CONFIG_INPUT_REQUIRED",
    "CONFIG_INVALID_VALUE",
    "CONFIG_JSON_INVALID",
    "CONFIG_UNKNOWN_FIELD",
    "FALLBACK_SECTION_INVALID",
    "INPUT_REQUIRED",
    "INVALID_INPUT",
    "IO_ERROR",
    "NOT_FOUND",
    "OUTPUT_REQUIRED",
    "PERMISSION_DENIED",
    "RECOVERY_SHARD_PAYLOADS_IGNORED",
    "RUNTIME_ERROR",
    "SIGNING_KEY_SHARD_DIR_EMPTY",
    "SIGNING_KEY_SHARD_DIR_INVALID",
    "SIGNING_KEY_SHARD_DIR_NOT_FOUND",
    "SHARD_DIR_EMPTY",
    "SHARD_DIR_INVALID",
    "SHARD_DIR_NOT_FOUND",
    "STABLE_BLOCKING_ISSUE_CODES",
    "STABLE_COMMAND_ERROR_CODES",
    "STABLE_GENERIC_ERROR_CODES",
    "STABLE_WARNING_CODES",
    "WARNING",
]
