from __future__ import annotations

from pathlib import Path
from typing import Protocol


class TaskMutationPort(Protocol):
    """Callbacks through which editors commit validated values to task state."""

    def _apply_backup_files_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_restore_sources_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_add_files_inputs_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_add_files_input_files_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_add_files_input_folder_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_rebuild_source_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_rebuild_backup_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_rebuild_scans_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_replace_recovery_sources_picked(
        self,
        paths: tuple[Path, ...] | None,
    ) -> None: ...

    def _apply_backup_output_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_restore_output_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_kit_output_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_add_files_backup_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_add_files_output_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_rebuild_output_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_replace_recovery_output_picked(
        self,
        paths: tuple[Path, ...] | None,
    ) -> None: ...

    def _apply_backup_passphrase(self, value: str | None) -> None: ...

    def _apply_restore_passphrase(self, value: str | None) -> None: ...

    def _apply_add_files_passphrase(self, value: str | None) -> None: ...

    def _apply_rebuild_passphrase(self, value: str | None) -> None: ...

    def _apply_replace_recovery_passphrase(self, value: str | None) -> None: ...

    def _apply_unlock_recovery_documents_picked(
        self,
        paths: tuple[Path, ...] | None,
    ) -> None: ...

    def _apply_unlock_payload_files_picked(
        self,
        paths: tuple[Path, ...] | None,
    ) -> None: ...

    def _apply_add_files_sources_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_add_files_base_dir_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_backup_base_dir_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_backup_signing_key_shards(self, value: str | None) -> None: ...

    def _apply_qr_chunk_size(self, value: str | None) -> None: ...

    def _apply_add_files_recovery_documents(self, value: str | None) -> None: ...

    def _apply_add_files_signing_key_shards(self, value: str | None) -> None: ...

    def _apply_restore_recovery_text(self, value: str | None) -> None: ...

    def _apply_restore_payloads_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_restore_auth_text_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_restore_auth_payloads_picked(
        self,
        paths: tuple[Path, ...] | None,
    ) -> None: ...

    def _apply_rebuild_auth_text_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_rebuild_auth_payloads_picked(
        self,
        paths: tuple[Path, ...] | None,
    ) -> None: ...

    def _apply_replace_recovery_text(self, value: str | None) -> None: ...

    def _apply_replace_payloads_picked(self, paths: tuple[Path, ...] | None) -> None: ...

    def _apply_replace_signing_key_payloads_picked(
        self,
        paths: tuple[Path, ...] | None,
    ) -> None: ...

    def _apply_backup_recovery(self, value: str | None) -> None: ...

    def _apply_replace_recovery_set(self, value: str | None) -> None: ...

    def _apply_replace_signing_key_recovery(self, value: str | None) -> None: ...

    def _apply_replace_passphrase_replacement_count(
        self,
        value: str | None,
    ) -> None: ...

    def _apply_replace_signing_key_replacement_count(
        self,
        value: str | None,
    ) -> None: ...

    def _apply_layout_section(self, value: str | None) -> None: ...

    def _apply_restore_target(self, value: str | None) -> None: ...

    def _apply_restore_target_fingerprint(self, value: str | None) -> None: ...

    def _apply_expected_head_fingerprint(self, value: str | None) -> None: ...
