#!/usr/bin/env python3
# Copyright (C) 2026 Alex Stoyanov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

from __future__ import annotations

NOT_FOUND = "NOT_FOUND"
INVALID_INPUT = "INVALID_INPUT"
RUNTIME_ERROR = "RUNTIME_ERROR"

INPUT_REQUIRED = "INPUT_REQUIRED"
OUTPUT_REQUIRED = "OUTPUT_REQUIRED"
ADD_FILES_INPUT_REQUIRED = "ADD_FILES_INPUT_REQUIRED"
ADD_FILES_NO_CHANGES = "ADD_FILES_NO_CHANGES"
ADD_FILES_NOT_REBUILDABLE = "ADD_FILES_NOT_REBUILDABLE"
ADD_FILES_RECOVERY_OUTPUT_EXISTS = "ADD_FILES_RECOVERY_OUTPUT_EXISTS"
ADD_FILES_RENDER_OPTIONS_INVALID = "ADD_FILES_RENDER_OPTIONS_INVALID"
EXTENSION_MAIN_CARRIER_INVALID = "EXTENSION_MAIN_CARRIER_INVALID"
EXTENSION_TOO_LARGE = "EXTENSION_TOO_LARGE"
EXTENSION_PUBLISH_TARGET_INVALID = "EXTENSION_PUBLISH_TARGET_INVALID"
REBUILD_INVALID_POLICY = "REBUILD_INVALID_POLICY"

WARNING = "WARNING"
AUTH_PAYLOAD_MISSING = "AUTH_PAYLOAD_MISSING"
AUTH_PAYLOAD_MULTIPLE = "AUTH_PAYLOAD_MULTIPLE"
AUTH_PAYLOAD_DOC_ID_MISMATCH = "AUTH_PAYLOAD_DOC_ID_MISMATCH"
AUTH_PAYLOAD_FRAME_INVALID = "AUTH_PAYLOAD_FRAME_INVALID"
AUTH_PAYLOAD_INVALID = "AUTH_PAYLOAD_INVALID"
AUTH_DOC_HASH_MISMATCH = "AUTH_DOC_HASH_MISMATCH"
AUTH_SIGNATURE_INVALID = "AUTH_SIGNATURE_INVALID"
AUTH_FALLBACK_INVALID = "AUTH_FALLBACK_INVALID"
FALLBACK_SECTION_INVALID = "FALLBACK_SECTION_INVALID"
RECOVERY_SHARD_PAYLOADS_IGNORED = "RECOVERY_SHARD_PAYLOADS_IGNORED"
BACKUP_SIGNING_KEY_SHARDING_DISABLED = "BACKUP_SIGNING_KEY_SHARDING_DISABLED"
BACKUP_QR_CHUNK_SIZE_REDUCED = "BACKUP_QR_CHUNK_SIZE_REDUCED"
ROOT_SIGNING_KEY_MISMATCH = "ROOT_SIGNING_KEY_MISMATCH"
RECOVERY_HEAD_UNTRUSTED = "RECOVERY_HEAD_UNTRUSTED"
PASSPHRASE_SHARDS_UNDER_QUORUM = "PASSPHRASE_SHARDS_UNDER_QUORUM"
PASSPHRASE_SHARDS_INVALID = "PASSPHRASE_SHARDS_INVALID"
PASSPHRASE_REQUIRED = "PASSPHRASE_REQUIRED"
AUTH_REQUIRED = "AUTH_REQUIRED"
SIGNING_KEY_SHARDS_REQUIRED = "SIGNING_KEY_SHARDS_REQUIRED"
SEALED_ROOT_CANNOT_ACCEPT_UPDATES = "SEALED_ROOT_CANNOT_ACCEPT_UPDATES"
CHAIN_INVALID = "CHAIN_INVALID"
DELETE_NOT_SUPPORTED = "DELETE_NOT_SUPPORTED"

__all__ = [
    "ADD_FILES_INPUT_REQUIRED",
    "ADD_FILES_NOT_REBUILDABLE",
    "ADD_FILES_NO_CHANGES",
    "ADD_FILES_RECOVERY_OUTPUT_EXISTS",
    "ADD_FILES_RENDER_OPTIONS_INVALID",
    "AUTH_DOC_HASH_MISMATCH",
    "AUTH_FALLBACK_INVALID",
    "AUTH_PAYLOAD_DOC_ID_MISMATCH",
    "AUTH_PAYLOAD_FRAME_INVALID",
    "AUTH_PAYLOAD_INVALID",
    "AUTH_PAYLOAD_MISSING",
    "AUTH_PAYLOAD_MULTIPLE",
    "AUTH_REQUIRED",
    "AUTH_SIGNATURE_INVALID",
    "BACKUP_QR_CHUNK_SIZE_REDUCED",
    "BACKUP_SIGNING_KEY_SHARDING_DISABLED",
    "CHAIN_INVALID",
    "DELETE_NOT_SUPPORTED",
    "EXTENSION_MAIN_CARRIER_INVALID",
    "EXTENSION_PUBLISH_TARGET_INVALID",
    "EXTENSION_TOO_LARGE",
    "FALLBACK_SECTION_INVALID",
    "INPUT_REQUIRED",
    "INVALID_INPUT",
    "NOT_FOUND",
    "OUTPUT_REQUIRED",
    "PASSPHRASE_REQUIRED",
    "PASSPHRASE_SHARDS_INVALID",
    "PASSPHRASE_SHARDS_UNDER_QUORUM",
    "REBUILD_INVALID_POLICY",
    "RECOVERY_HEAD_UNTRUSTED",
    "RECOVERY_SHARD_PAYLOADS_IGNORED",
    "ROOT_SIGNING_KEY_MISMATCH",
    "RUNTIME_ERROR",
    "SEALED_ROOT_CANNOT_ACCEPT_UPDATES",
    "SIGNING_KEY_SHARDS_REQUIRED",
    "WARNING",
]
