name: Setup Python with uv
description: Set up Python, uv, and install dependencies with caching

inputs:
  python-version:
    description: Python version to use
    required: false
    default: "3.13"
  extras:
    description: Extra dependencies to install (comma-separated)
    required: false
    default: "dev"

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up uv
      uses: astral-sh/setup-uv@8d55fbecc275b1c35dbe060458839f8d30439ccf # v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install dependencies
      shell: bash
      run: uv sync --extra ${{ inputs.extras }} --frozen
