# Copyright (C) 2026 Alex Stoyanov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

import base64
import unittest
from pathlib import Path

from ethernity.render.templating import render_template

_PROJECT_ROOT = Path(__file__).resolve().parents[2]
_ETHERNITY_ROOT = _PROJECT_ROOT / "src" / "ethernity"
_MAIN_SUBTITLE = "Passphrase-protected payload"


def _page_base(*, page_num: int, page_label: str) -> dict[str, object]:
    return {
        "page_num": page_num,
        "page_label": page_label,
        "divider_y_mm": 30.0,
        "instructions_y_mm": 40.0,
        "show_instructions": True,
        "instructions_full_page": False,
        "qr_items": [],
        "qr_grid": None,
        "qr_outline": None,
        "sequence": None,
        "fallback_blocks": [],
    }


def _page_with_qr(*, page_num: int = 1, page_label: str = "Page 1 / 1") -> dict[str, object]:
    page = _page_base(page_num=page_num, page_label=page_label)
    page["qr_items"] = [{"index": 1, "data_uri": "data:image/png;base64,AA=="}]
    page["qr_grid"] = {
        "x_mm": 14.0,
        "y_mm": 60.0,
        "size_mm": 50.0,
        "gap_x_mm": 2.0,
        "gap_y_mm": 2.0,
        "cols": 3,
        "rows": 1,
        "count": 1,
    }
    page["qr_outline"] = {"x_mm": 14.0, "y_mm": 60.0, "width_mm": 50.0, "height_mm": 50.0}
    return page


def _base_document_context() -> dict[str, object]:
    return {
        "page_size_css": "A4",
        "page_width_mm": 210.0,
        "page_height_mm": 297.0,
        "margin_mm": 14.0,
        "usable_width_mm": 182.0,
        "doc_id": "deadbeef" * 4,
        "created_timestamp_utc": "2026-01-01 00:00 UTC",
        "doc": {"title": "Document", "subtitle": "Subtitle"},
        "instructions": {"label": "Instructions", "lines": ["Line 1", "Line 2"], "scan_hint": None},
        "keys": {"lines": []},
        "fallback": {"width_mm": 182.0},
        "forge_copy": {
            "doc_id_label": "DOC ID",
            "generated_utc_label": "GENERATED (UTC)",
            "version": "v2.1",
            "generator_label": "Generated by Ethernity Forge",
            "protocol_label": "Ethernity Forge Security Protocols",
            "backup_system_label": "The Forge Secure Backup System",
        },
        "shard_index": 1,
        "shard_total": 3,
        "recovery": {
            "passphrase": None,
            "passphrase_lines": [],
            "quorum_value": None,
            "signing_pub_lines": [],
        },
    }


class TestJinjaTemplates(unittest.TestCase):
    def _render_sentinel_template(self, template_name: str) -> str:
        template_path = _ETHERNITY_ROOT / "templates" / "sentinel" / template_name
        context = _base_document_context()
        if template_name == "main_document.html.j2":
            context["pages"] = [_page_with_qr(page_num=1, page_label="Page 1 / 1")]
            context["doc"] = {"title": "Main Document", "subtitle": _MAIN_SUBTITLE}
            context["instructions"] = {
                "label": "Instructions",
                "lines": ["A", "B"],
                "scan_hint": "Start at the top-left and follow each row.",
            }
        elif template_name == "recovery_document.html.j2":
            context["pages"] = [
                {
                    **_page_base(page_num=1, page_label="Page 1 / 2"),
                    "fallback_blocks": [
                        {
                            "title": "AUTH FRAME",
                            "lines": [f"line-{idx:02d}" for idx in range(1, 8)],
                            "line_offset": 0,
                            "y_mm": 90.0,
                            "height_mm": 80.0,
                        }
                    ],
                },
                {
                    **_page_base(page_num=2, page_label="Page 2 / 2"),
                    "show_instructions": False,
                    "fallback_blocks": [
                        {
                            "title": None,
                            "lines": [f"line-{idx:02d}" for idx in range(8, 18)],
                            "line_offset": 7,
                            "y_mm": 90.0,
                            "height_mm": 80.0,
                        }
                    ],
                },
            ]
            context["doc"] = {"title": "Recovery Document", "subtitle": "Keys + Text Fallback"}
        elif template_name == "kit_document.html.j2":
            context["pages"] = [
                _page_with_qr(page_num=1, page_label="Page 1 / 2"),
                {
                    **_page_base(page_num=2, page_label="Page 2 / 2"),
                    "instructions_full_page": True,
                },
            ]
            context["doc"] = {"title": "Recovery Kit", "subtitle": "Offline HTML bundle"}
            context["instructions"] = {
                "label": "Instructions",
                "lines": ["A", "B"],
                "scan_hint": "Start at the top-left and follow each row.",
            }
        elif template_name == "kit_index_document.html.j2":
            context["pages"] = [
                _page_with_qr(page_num=1, page_label="Page 1 / 1"),
            ]
            context["doc"] = {"title": "Recovery Kit", "subtitle": "Offline HTML bundle"}
            context["inventory_rows"] = [
                {
                    "component_id": "QR-DOC-01",
                    "detail": "Encrypted payload and auth QR frames",
                    "status": "Generated",
                },
                {
                    "component_id": "RECOVERY-DOC-01",
                    "detail": "Recovery keys and full fallback text",
                    "status": "Generated",
                },
            ]
        elif template_name in {"shard_document.html.j2", "signing_key_shard_document.html.j2"}:
            context["pages"] = [
                {
                    **_page_with_qr(page_num=1, page_label="Page 1 / 1"),
                    "fallback_blocks": [
                        {
                            "title": "MAIN",
                            "lines": ["aaaa bbbb cccc dddd", "eeee ffff gggg hhhh"],
                            "line_offset": 0,
                            "y_mm": 90.0,
                            "height_mm": 80.0,
                        }
                    ],
                }
            ]
            context["shard_threshold"] = 2
            context["doc"] = {
                "title": "Signing Key Shard"
                if template_name == "signing_key_shard_document.html.j2"
                else "Shard Document",
                "subtitle": "Shard 1 of 3",
            }
        else:
            raise AssertionError(f"unexpected sentinel template: {template_name}")
        return render_template(template_path, context)

    def test_document_templates_render(self) -> None:
        template_root = _ETHERNITY_ROOT / "templates"
        templates = sorted(template_root.rglob("*.html.j2"))
        self.assertTrue(templates, "no document templates found")

        for template_path in templates:
            context = _base_document_context()
            if "recovery_document" in template_path.name:
                context["pages"] = [_page_base(page_num=1, page_label="Page 1 / 1")]
                context["doc"] = {"title": "Recovery Document", "subtitle": "Keys + Text Fallback"}
                context["instructions"] = {
                    "label": "Instructions",
                    "lines": ["A", "B"],
                    "scan_hint": None,
                }
            elif "kit_document" in template_path.name:
                context["pages"] = [
                    _page_with_qr(page_num=1, page_label="Page 1 / 2"),
                    {
                        **_page_base(page_num=2, page_label=""),
                        "instructions_full_page": True,
                        "qr_items": [],
                    },
                ]
                context["doc"] = {"title": "Recovery Kit", "subtitle": "Offline HTML bundle"}
                context["instructions"] = {
                    "label": "Instructions",
                    "lines": ["A", "B"],
                    "scan_hint": "Start at the top-left and follow each row.",
                }
            elif (
                "shard_document" in template_path.name
                or "signing_key_shard_document" in template_path.name
            ):
                context["pages"] = [
                    {
                        **_page_with_qr(page_num=1, page_label="Page 1 / 1"),
                        "fallback_blocks": [
                            {
                                "title": "MAIN",
                                "lines": ["aaaa bbbb cccc dddd", "eeee ffff gggg hhhh"],
                                "line_offset": 0,
                                "y_mm": 90.0,
                                "height_mm": 80.0,
                            }
                        ],
                    }
                ]
                context["doc"] = {"title": "Shard Document", "subtitle": "Shard 1 of 3"}
                context["instructions"] = {
                    "label": "Instructions",
                    "lines": ["A", "B"],
                    "scan_hint": None,
                }
            else:
                context["pages"] = [_page_with_qr(page_num=1, page_label="Page 1 / 1")]
                context["doc"] = {"title": "Main Document", "subtitle": _MAIN_SUBTITLE}
                context["instructions"] = {
                    "label": "Instructions",
                    "lines": ["A", "B"],
                    "scan_hint": None,
                }

            rendered = render_template(template_path, context)
            self.assertIn("<!doctype html>", rendered.lower(), str(template_path))

    def test_envelope_templates_render_with_default_logo(self) -> None:
        storage_root = _ETHERNITY_ROOT / "storage"
        logo_path = storage_root / "logo.png"
        self.assertTrue(logo_path.is_file(), "expected default logo.png to exist")

        prefix = base64.b64encode(logo_path.read_bytes()[:60]).decode("ascii")

        templates = sorted(storage_root.glob("envelope_*.html.j2"))
        self.assertTrue(templates, "no envelope templates found")

        for template_path in templates:
            rendered = render_template(
                template_path,
                {"page_width_mm": 114, "page_height_mm": 162},
            )
            self.assertIn("base64,", rendered, str(template_path))
            self.assertIn(prefix, rendered, str(template_path))

    def test_forge_qr_labels_use_global_slot_index(self) -> None:
        context = _base_document_context()
        context["doc"] = {"title": "Main Document", "subtitle": _MAIN_SUBTITLE}
        context["pages"] = [
            {
                **_page_base(page_num=2, page_label="Page 2 / 3"),
                "qr_items": [
                    {"index": 13, "data_uri": "data:image/png;base64,AA=="},
                ],
                "qr_grid": {
                    "x_mm": 14.0,
                    "y_mm": 60.0,
                    "size_mm": 50.0,
                    "gap_x_mm": 2.0,
                    "gap_y_mm": 2.0,
                    "cols": 3,
                    "rows": 1,
                    "count": 1,
                },
            }
        ]

        main_template = _ETHERNITY_ROOT / "templates" / "forge" / "main_document.html.j2"
        main_rendered = render_template(main_template, context)
        self.assertIn("PART 13", main_rendered)

        kit_context = _base_document_context()
        kit_context["doc"] = {"title": "Recovery Kit", "subtitle": "Offline HTML bundle"}
        kit_context["pages"] = [
            {
                **_page_base(page_num=2, page_label="Page 2 / 4"),
                "qr_items": [
                    {"index": 7, "data_uri": "data:image/png;base64,AA=="},
                ],
                "qr_grid": {
                    "x_mm": 14.0,
                    "y_mm": 60.0,
                    "size_mm": 50.0,
                    "gap_x_mm": 2.0,
                    "gap_y_mm": 2.0,
                    "cols": 3,
                    "rows": 1,
                    "count": 1,
                },
                "instructions_full_page": False,
            }
        ]

        kit_template = _ETHERNITY_ROOT / "templates" / "forge" / "kit_document.html.j2"
        kit_rendered = render_template(kit_template, kit_context)
        self.assertIn("KIT 07", kit_rendered)

    def test_forge_wording_uses_canonical_labels_and_versions(self) -> None:
        forge_root = _ETHERNITY_ROOT / "templates" / "forge"

        main_context = _base_document_context()
        main_context["pages"] = [_page_with_qr(page_num=1, page_label="Page 1 / 1")]
        main_context["doc"] = {"title": "Main Document", "subtitle": _MAIN_SUBTITLE}
        main_rendered = render_template(forge_root / "main_document.html.j2", main_context)
        self.assertIn("DOC ID:", main_rendered)
        self.assertIn("GENERATED (UTC):", main_rendered)
        self.assertIn("The Forge Secure Backup System v2.1", main_rendered)
        self.assertNotIn("UNIQUE ID:", main_rendered)

        recovery_context = _base_document_context()
        recovery_context["pages"] = [_page_base(page_num=1, page_label="Page 1 / 1")]
        recovery_context["doc"] = {"title": "Recovery Document", "subtitle": "Keys + Text Fallback"}
        recovery_rendered = render_template(
            forge_root / "recovery_document.html.j2",
            recovery_context,
        )
        self.assertIn("DOC ID:", recovery_rendered)
        self.assertIn("GENERATED (UTC):", recovery_rendered)
        self.assertNotIn("SHEET ID:", recovery_rendered)

        kit_context = _base_document_context()
        kit_context["doc"] = {"title": "Recovery Kit", "subtitle": "Offline HTML bundle"}
        kit_context["pages"] = [
            _page_with_qr(page_num=1, page_label="Page 1 / 2"),
            {
                **_page_base(page_num=2, page_label=""),
                "instructions_full_page": True,
                "qr_items": [],
            },
        ]
        kit_rendered = render_template(forge_root / "kit_document.html.j2", kit_context)
        self.assertIn("GENERATED (UTC)", kit_rendered)
        self.assertIn("DOC ID", kit_rendered)
        self.assertIn("Ethernity Forge Security Protocols v2.1", kit_rendered)
        self.assertNotIn("Generated On", kit_rendered)
        self.assertNotIn("Kit ID", kit_rendered)
        self.assertNotIn("v2.4", kit_rendered)

        shard_context = _base_document_context()
        shard_context["doc"] = {"title": "Shard Document", "subtitle": "Shard 1 of 3"}
        shard_context["pages"] = [_page_with_qr(page_num=1, page_label="Page 1 / 1")]
        shard_rendered = render_template(forge_root / "shard_document.html.j2", shard_context)
        self.assertIn("DOC ID:", shard_rendered)
        self.assertIn("Ethernity Forge Security Protocols v2.1", shard_rendered)
        self.assertNotIn("Ethernity Protocol v2.0", shard_rendered)

        signing_context = _base_document_context()
        signing_context["doc"] = {
            "title": "Signing Key Shard",
            "subtitle": "Signing key shard 1 of 3",
        }
        signing_context["pages"] = [
            {
                **_page_with_qr(page_num=1, page_label="Page 1 / 1"),
                "fallback_blocks": [
                    {
                        "title": "MAIN",
                        "lines": ["aaaa bbbb cccc dddd", "eeee ffff gggg hhhh"],
                        "line_offset": 0,
                        "y_mm": 90.0,
                        "height_mm": 80.0,
                    }
                ],
            }
        ]
        signing_rendered = render_template(
            forge_root / "signing_key_shard_document.html.j2",
            signing_context,
        )
        self.assertIn("DOC ID:", signing_rendered)
        self.assertIn("GENERATED (UTC):", signing_rendered)
        self.assertIn("Forge v2.1", signing_rendered)
        self.assertIn("Generated by Ethernity Forge", signing_rendered)
        self.assertNotIn("DOC-ID:", signing_rendered)
        self.assertNotIn("Generated by Ethernity Vault", signing_rendered)
        self.assertNotIn("Session ID:", signing_rendered)

    def test_forge_templates_use_local_material_symbols_font(self) -> None:
        forge_root = _ETHERNITY_ROOT / "templates" / "forge"

        for template_path in sorted(forge_root.glob("*_document.html.j2")):
            with self.subTest(template=template_path.name):
                context = _base_document_context()
                if template_path.name == "recovery_document.html.j2":
                    context["pages"] = [_page_base(page_num=1, page_label="Page 1 / 1")]
                    context["doc"] = {
                        "title": "Recovery Document",
                        "subtitle": "Keys + Text Fallback",
                    }
                elif template_path.name == "kit_document.html.j2":
                    context["pages"] = [
                        _page_with_qr(page_num=1, page_label="Page 1 / 2"),
                        {**_page_base(page_num=2, page_label=""), "instructions_full_page": True},
                    ]
                    context["doc"] = {"title": "Recovery Kit", "subtitle": "Offline HTML bundle"}
                elif template_path.name in {
                    "shard_document.html.j2",
                    "signing_key_shard_document.html.j2",
                }:
                    context["pages"] = [_page_with_qr(page_num=1, page_label="Page 1 / 1")]
                    context["doc"] = {"title": "Shard Document", "subtitle": "Shard 1 of 3"}
                else:
                    context["pages"] = [_page_with_qr(page_num=1, page_label="Page 1 / 1")]
                    context["doc"] = {"title": "Main Document", "subtitle": _MAIN_SUBTITLE}
                rendered = render_template(template_path, context)
                self.assertIn(
                    "https://ethernity.local/assets/material-symbols-outlined.ttf",
                    rendered,
                )
                self.assertNotIn("fonts.googleapis.com", rendered)

    def test_forge_templates_render_mock_icon_ligatures(self) -> None:
        forge_root = _ETHERNITY_ROOT / "templates" / "forge"
        expected_icons_by_template = {
            "main_document.html.j2": ["visibility_off", "lock", "content_cut"],
            "recovery_document.html.j2": ["shield_lock", "warning", "fingerprint", "verified_user"],
            "shard_document.html.j2": ["warning"],
            "signing_key_shard_document.html.j2": [
                "token",
                "shield_lock",
                "vpn_key",
                "visibility",
                "settings_ethernet",
            ],
            "kit_document.html.j2": [
                "token",
                "qr_code_2",
                "warning",
                "verified_user",
                "check_box_outline_blank",
                "lock",
            ],
            "kit_index_document.html.j2": [
                "qr_code_2",
                "warning",
                "inventory_2",
                "verified_user",
                "lock",
            ],
        }

        for template_name, expected_icons in expected_icons_by_template.items():
            template_path = forge_root / template_name
            with self.subTest(template=template_name):
                context = _base_document_context()
                if template_name == "recovery_document.html.j2":
                    context["pages"] = [_page_base(page_num=1, page_label="Page 1 / 1")]
                    context["doc"] = {
                        "title": "Recovery Document",
                        "subtitle": "Keys + Text Fallback",
                    }
                elif template_name == "kit_document.html.j2":
                    context["pages"] = [
                        _page_with_qr(page_num=1, page_label="Page 1 / 2"),
                        {**_page_base(page_num=2, page_label=""), "instructions_full_page": True},
                    ]
                    context["doc"] = {"title": "Recovery Kit", "subtitle": "Offline HTML bundle"}
                elif template_name == "kit_index_document.html.j2":
                    context["pages"] = [_page_with_qr(page_num=1, page_label="Page 1 / 1")]
                    context["doc"] = {"title": "Recovery Kit", "subtitle": "Offline HTML bundle"}
                elif template_name in {
                    "shard_document.html.j2",
                    "signing_key_shard_document.html.j2",
                }:
                    context["pages"] = [
                        {
                            **_page_with_qr(page_num=1, page_label="Page 1 / 1"),
                            "fallback_blocks": [
                                {
                                    "title": "MAIN",
                                    "lines": ["aaaa bbbb cccc dddd", "eeee ffff gggg hhhh"],
                                    "line_offset": 0,
                                    "y_mm": 90.0,
                                    "height_mm": 80.0,
                                }
                            ],
                        }
                    ]
                    context["doc"] = {"title": "Shard Document", "subtitle": "Shard 1 of 3"}
                else:
                    context["pages"] = [_page_with_qr(page_num=1, page_label="Page 1 / 1")]
                    context["doc"] = {"title": "Main Document", "subtitle": _MAIN_SUBTITLE}
                    context["instructions"] = {
                        "label": "Instructions",
                        "lines": ["A", "B", "C"],
                        "scan_hint": "Start at the top-left and follow each row.",
                    }

                rendered = render_template(template_path, context)
                for icon in expected_icons:
                    self.assertIn(icon, rendered)

    def test_forge_recovery_template_uses_fixed_print_sheet_and_nonflowing_footer(self) -> None:
        forge_root = _ETHERNITY_ROOT / "templates" / "forge"
        template_path = forge_root / "recovery_document.html.j2"
        context = _base_document_context()
        context["doc"] = {"title": "Recovery Document", "subtitle": "Keys + Text Fallback"}
        context["pages"] = [
            _page_base(page_num=1, page_label="Page 1 / 2"),
            {
                **_page_base(page_num=2, page_label="Page 2 / 2"),
                "show_instructions": False,
                "fallback_blocks": [
                    {
                        "title": None,
                        "lines": [f"line-{idx:02d}" for idx in range(1, 41)],
                        "line_offset": 0,
                        "y_mm": 70.0,
                        "height_mm": 200.0,
                    }
                ],
            },
        ]

        rendered = render_template(template_path, context)
        self.assertIn("height: 297.0mm;", rendered)
        self.assertIn("overflow: hidden;", rendered)
        self.assertIn("display: block !important;", rendered)
        self.assertIn('class="flex-1 min-h-0 mb-4"', rendered)
        self.assertIn('class="mt-2 shrink-0 pt-4 border-t border-slate-200', rendered)

    def test_forge_kit_index_template_paginates_inventory_rows(self) -> None:
        forge_root = _ETHERNITY_ROOT / "templates" / "forge"
        template_path = forge_root / "kit_index_document.html.j2"
        context = _base_document_context()
        context["doc"] = {"title": "Recovery Kit", "subtitle": "Offline HTML bundle"}
        context["pages"] = [_page_with_qr(page_num=1, page_label="Page 1 / 1")]
        context["inventory_rows"] = [
            {
                "component_id": f"COMP-{idx:02d}",
                "detail": f"Detail {idx}",
                "status": "Generated",
            }
            for idx in range(1, 28)
        ]

        rendered = render_template(template_path, context)
        self.assertIn("COMP-01", rendered)
        self.assertIn("COMP-27", rendered)
        self.assertGreater(rendered.count('<section class="print-sheet'), 1)
        self.assertNotIn("additional entries", rendered)
        self.assertEqual(rendered.count("Custodian Signature"), 1)

    def test_sentinel_templates_use_local_tailwind_runtime(self) -> None:
        tailwind_asset = (
            _ETHERNITY_ROOT
            / "templates"
            / "_shared"
            / "assets"
            / "tailwindcss-playcdn-forms-container-queries.js"
        )
        self.assertTrue(tailwind_asset.is_file())

        sentinel_root = _ETHERNITY_ROOT / "templates" / "sentinel"
        for template_path in sorted(sentinel_root.glob("*_document.html.j2")):
            with self.subTest(template=template_path.name):
                source = template_path.read_text(encoding="utf-8")
                self.assertIn("sentinel_tailwind_setup.j2", source)
                self.assertNotIn("cdn.tailwindcss.com", source)
                self.assertNotIn("fonts.googleapis.com", source)

    def test_sentinel_templates_use_shared_shell_hooks(self) -> None:
        sentinel_templates = [
            "main_document.html.j2",
            "recovery_document.html.j2",
            "kit_document.html.j2",
            "kit_index_document.html.j2",
            "shard_document.html.j2",
            "signing_key_shard_document.html.j2",
        ]
        for template_name in sentinel_templates:
            with self.subTest(template=template_name):
                rendered = self._render_sentinel_template(template_name)
                self.assertIn("sentinel-shell-top-strip", rendered)
                self.assertIn("sentinel-shell-header", rendered)
                self.assertIn("sentinel-shell-footer", rendered)
                self.assertNotIn("bg-hazard-pattern", rendered)
                self.assertNotIn("repeating-linear-gradient(45deg,#cf3030", rendered)

    def test_sentinel_recovery_uses_same_shell_on_continuation_pages(self) -> None:
        rendered = self._render_sentinel_template("recovery_document.html.j2")
        self.assertEqual(rendered.count("sentinel-shell-top-strip"), 2)
        self.assertEqual(rendered.count("sentinel-shell-header"), 2)
        self.assertEqual(rendered.count("sentinel-shell-footer"), 2)
        self.assertIn("DOC ID:", rendered)
        self.assertIn("GENERATED (UTC):", rendered)

    def test_sentinel_shard_templates_show_threshold_as_k_of_n(self) -> None:
        signing_rendered = self._render_sentinel_template("signing_key_shard_document.html.j2")
        self.assertIn("Threshold: 2/3 required", signing_rendered)

        shard_rendered = self._render_sentinel_template("shard_document.html.j2")
        self.assertIn("Recovery requires 2/3 shards.", shard_rendered)

    def test_monograph_templates_use_local_tailwind_runtime(self) -> None:
        tailwind_asset = (
            _ETHERNITY_ROOT
            / "templates"
            / "_shared"
            / "assets"
            / "tailwindcss-playcdn-forms-container-queries.js"
        )
        self.assertTrue(tailwind_asset.is_file())

        monograph_root = _ETHERNITY_ROOT / "templates" / "monograph"
        for template_path in sorted(monograph_root.glob("*_document.html.j2")):
            with self.subTest(template=template_path.name):
                source = template_path.read_text(encoding="utf-8")
                self.assertIn("monograph_tailwind_setup.j2", source)
                self.assertNotIn("cdn.tailwindcss.com", source)
                self.assertNotIn("fonts.googleapis.com", source)


if __name__ == "__main__":
    unittest.main()
